### PR TITLE
HTTP Proxy support for Pushy

### PR DESCRIPTION
**Pull request by PhilipGough**
ping @maleck13 @ziccardi

### CODE REVIEW

**Comment by ziccardi** [comment]
Wouldn't be better to support both socks and HTTP proxy?

**Comment by ziccardi** [comment]
LGTM

**Comment by PhilipGough** [comment]
Verified push and Nagios dashboard on osm3 with @luigizuccarelli

**Comment by matzew** [comment]
@ziccardi @PhilipGough @maleck13 why was this not submitted to upstream ?

**Comment by matzew** [comment]
For the record, code that also is relevant for the community, like this one, always has to be merged against upstream.

We will do a rebase _afterwards_ to get the Java fix to here

**Pull request merged**
