### PR TITLE
update Dockerfile

### PR DESCRIPTION
**Pull request by StephenCoady**
**JIRA**
https://issues.jboss.org/browse/RHMAP-19219

**Changes**
It looks like the dev image has fallen out of sync with the productised image, and the build up until this point (on wendy) may have been using an out of date base image. This Dockerfile brings the images back in sync.

**Verification**
1. Deploy a core using the template created in https://github.com/fheng/fh-core-openshift-templates/pull/1199
2. Verify UPS starts and runs correctly in the core

### CODE REVIEW

**Comment by jessesarn** [comment]
@StephenCoady Be sure to link the PR to the JIRA so that other team members can see it needs to be reviewed from the team's Kanban board.

**Comment by StephenCoady** [comment]
@jessesarn as soon as its done I will. There is still a bit of figuring out to be done around the build.

**Comment by mikenairn** [comment]
@StephenCoady So we have combined the eap and ups into one Dockerfile and it now exactly matches what we do for our productized image right?

**Comment by StephenCoady** [comment]
@mikenairn correct. Its what Bob would have done, just in one Dockerfile as opposed to two.

**Pull request merged**
