### PR TITLE
Adding details about the actual variant on PUT request for update

### PR DESCRIPTION
**Pull request by matzew**
cherry pick, from upstream

### CODE REVIEW

**Comment by matzew** [comment]
@lfryc @wei-lee mind to check / review ? 

btw. is there no bob build ? Not sure how to trigger - I guess the bob build is needed, to get this version shipped to fhcap, no ?

**Comment by wei-lee** [comment]
@matzew LGTM. Do we need to bump version or anything like that? Looks like we can trigger the build manually. I have started a build and let's see if it will build.

**Comment by matzew** [comment]
we should perhaps do a version bump, to indicate the 3.6.1 nature ?

On Mon, Dec 7, 2015 at 11:57 AM, Wei Li <notifications@github.com> wrote:

> @matzew <https://github.com/matzew> LGTM. Do we need to bump version or
> anything like that? Looks like we can trigger the build manually. I have
> started a build and let's see if it will build.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fheng/aerogear-unifiedpush-server/pull/4#issuecomment-162482469>
> .
>



-- 
Matthias Wessendorf

blog: http://matthiaswessendorf.wordpress.com/
sessions: http://www.slideshare.net/mwessendorf
twitter: http://twitter.com/mwessendorf

**Comment by wei-lee** [comment]
@matzew Any idea how to do the version bump? Update fhcap? The build on bob is passed BTW: http://bob.feedhenry.net:8080/job/aerogear-unifiedpush-server/13/

**Comment by matzew** [comment]
i thnk we just used the build nr. that should be good enough.
lemme update fhcap

On Monday, 7 December 2015, Wei Li <notifications@github.com> wrote:

> @matzew <https://github.com/matzew> Any idea how to do the version bump?
> Update fhcap? The build on bob is passed BTW:
> http://bob.feedhenry.net:8080/job/aerogear-unifiedpush-server/13/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fheng/aerogear-unifiedpush-server/pull/4#issuecomment-162496613>
> .
>


-- 
Sent from Gmail Mobile

**Comment by wei-lee** [comment]
@matzew ok. Make sure use the FH-v3.6.1 branch of fhcap.

**Comment by lfryc** [comment]
@matzew @wei-lee I designed the build to build from tag + version number.

Use of both seems to be sufficient to uniquely identify binary.

**Comment by matzew** [comment]
@lfryc I think that's what I did here:

https://github.com/fheng/fhcap/pull/1293

**Comment by lfryc** [comment]
@matzew yea, I just reading the github updates in chronological order :-)

**Pull request merged**
