### PR TITLE
dummy

### PR DESCRIPTION
**Pull request by matzew**

### CODE REVIEW

**Comment by matzew** [comment]
@mikenairn @grdryn is this supposed to trigger a dependent build for the docker stff ?

I think it was the case in the past ... or did that recently change ?

**Comment by matzew** [comment]
it did ! :smile_cat:

**Comment by matskiv** [comment]
Retest this please

**Comment by matskiv** [comment]
@matzew Let me use your "dummy PR" to test changes to docker image config :D

**Comment by matzew** [comment]
yeah, those are gold :) :medal_sports: 

but @ziccardi will be working on one Jenkins job

**Comment by matzew** [comment]
out dated, closoing

**Pull request closed without merging**
