### PR TITLE
dummy

### PR DESCRIPTION
**Pull request by matzew**

### CODE REVIEW

**Comment by matzew** [comment]
@grdryn not 100% what to do with these dyummy PRs, to tigger a new build :) 

and how to update the version for 4.3

**Comment by grdryn** [comment]
@matzew I had to make [a dummy commit](https://github.com/fheng/aerogear-unifiedpush-server/pull/19) to generate a new build for new changes in the fheng/ups-dockerfiles repo (since there's no job there). We previously had this problem with lots of the FeedHenry components when we had a separate repo called fh-dockerfiles for the docker stuff. We've since moved that stuff back into the component repos themselves, so we don't have a problem any longer. I'm not sure if that's something you want to consider here?

Looking at your scenario, it looks like you need to do it because you've cherry-picked changes from upstream onto the branch here, is that right? When doing that, you could get a new build easily by first branching from target branch, cherry-picking the commits onto that new branch, then creating a PR from there back to the target branch. Then when the build passes, merge that branch back to the target branch, similar to how we do things with the other components.

Does that sound like a reasonable approach to get what you want?

**Comment by matzew** [comment]
I basically rebased from upstream 1.1.x branch, we have some bogus RHMAP specific commits here.

all I want is to shipt his to the 4.3

**Comment by grdryn** [comment]
@matzew yeah, it's probably ok to do it like this for now. I think next time it might be easier to do it the way I outlined above, so that you don't have to make a different commit.

Also, note that the downstream jobs to update the templates repo (and usually fhcap, but this doesn't seem to trigger an fhcap update. Should it?) will PR to a branch that corresponds to the target branch in your original PR (this one). So in this case, you can see that the corresponding [fh-core-openshift-templates](https://github.com/fheng/fh-core-openshift-templates/issues/340) targets ups_rhmap_3.16.x there. Is that okay, or should it be going back to some other branch? I don't see a 4.3 branch of the templates yet. Maybe these changes should be going to master of the template repo?

Should these changes be included in the next fhcap/RHMAP3 release also?

**Comment by matzew** [comment]
@grdryn 

1) about FHCAP, for now is done manually via custom build in:
http://bob.feedhenry.net:8080/job/aerogear-unifiedpush-server%20(deprecated)/
and than I sent a PR, like here:
https://github.com/fheng/fhcap/pull/4179

2) fh-core-openshift-templagtes
Yes, that branch is good, and should be used for 4.3 RHMAP release; the other questions I don't understand, because i have never worked on the templates. all I know is that this version of UPS should go to the docker image that is part of 4.3 

so, we can merge:
https://github.com/fheng/fh-core-openshift-templates/pull/340

and than close this ?

**Comment by grdryn** [comment]
@matzew sorry for the delayed reply, I was on PTO yesterday. :)

So I think if you're happy with this branch here, this can be closed. I'm not sure about the fh-core-openshift-templates one though: I don't think the target branch there would be considered a release branch. AIUI the release branch there would be created at code freeze from master, and will be called something like FH-v3.16.0.

Maybe we should close that PR, and manually create one against the master branch of fh-core-openshift-templates, WDYT? With that line of thinking, would the changes here in aerogear-unifiedpush-server be expected to go back to the rhmap branch also (or are they already on that branch)?

**Comment by matzew** [comment]
@grdryn we should be using this TAG (not a branch):
https://github.com/fheng/aerogear-unifiedpush-server/tree/1.1.4.Final-rhmap-13

that's what's landing in 3.16 / SaaS

**Pull request closed without merging**
