### PR TITLE
added ids for easily testable ui

### PR DESCRIPTION
**Pull request by thradec**

### CODE REVIEW

**Comment by lfryc** [comment]
:+1: I will test it and merge today

**Comment by lfryc** [comment]
Merged to https://github.com/fheng/aerogear-unifiedpush-server/tree/fh_push_admin_ui

**Comment by thradec** [comment]
Thanks @lfryc ;-)

**Comment by lfryc** [comment]
This will be merged to UPS `master` with https://issues.jboss.org/browse/AGPUSH-1518

**Pull request closed without merging**
